DROP DATABASE IF EXISTS SPJ;
CREATE DATABASE SPJ;
USE SPJ;

DROP TABLE IF EXISTS S;
CREATE TABLE S(
    `SNO` CHAR(6) PRIMARY KEY,
    `SNAME` VARCHAR(20) NOT NULL,
    `STATUS` VARCHAR(50),
    `CITY` VARCHAR(50)
);

DROP TABLE IF EXISTS P;
CREATE TABLE P (
    `PNO` CHAR(6) PRIMARY KEY,
    `PNAME` VARCHAR(20) NOT NULL,
    `COLOR` CHAR(2),
    `WEIGHT` NUMERIC(9,2)
    CHECK(WEIGHT>0 AND WEIGHT < 100)
);

DROP TABLE IF EXISTS J;
CREATE TABLE J (
    `JNO` CHAR(6) PRIMARY KEY,
    `JNAME` VARCHAR(20) NOT NULL,
    `CITY` VARCHAR(50)
);

DROP TABLE IF EXISTS SPJ;
CREATE TABLE SPJ (
    `SNO` CHAR(6) NOT NULL,
    `PNO` CHAR(6) NOT NULL,
    `JNO` CHAR(6) NOT NULL,
    `QTY` SMALLINT DEFAULT 100
);

ALTER TABLE P ADD `STANDARD` CHAR(50);

ALTER TABLE SPJ ADD CONSTRAINT `FK_SNO` FOREIGN KEY (`SNO`) REFERENCES `S` (`SNO`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE SPJ ADD CONSTRAINT `FK_PNO` FOREIGN KEY (`PNO`) REFERENCES `P` (`PNO`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE SPJ ADD CONSTRAINT `FK_JNO` FOREIGN KEY (`JNO`) REFERENCES `J` (`JNO`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE P DROP `STANDARD`;

DROP DATABASE IF EXISTS school;
CREATE DATABASE school;

USE school;

DROP TABLE IF EXISTS Student;
CREATE TABLE Student(
    `SNO` CHAR(7) PRIMARY KEY,
    `SNAME` CHAR(10) NOT NULL,
    `SSEX` CHAR(3),
    `SAGE` SMALLINT,
    `SDEPT` VARCHAR(20) DEFAULT '计算机系',
    CHECK (SSEX = '男' OR SSEX = '女'),
    CHECK (SAGE >= 15 AND SAGE <= 45)
);

DROP TABLE IF EXISTS Course;
CREATE TABLE Course (
    `CNO` CHAR(10) PRIMARY KEY,
    `CNAME` VARCHAR(20) NOT NULL,
    `CCREDIT` SMALLINT,
    `SEMSTER` SMALLINT,
    `PERIOD` SMALLINT,
    CHECK (CCREDIT > 0),
    CHECK (SEMSTER > 0),
    CHECK (PERIOD > 0)
);

DROP TABLE IF EXISTS SC;
CREATE TABLE SC (
    `SNO` CHAR(7),
    `CNO` CHAR(10),
    `GRADE` SMALLINT,
    CHECK (`GRADE` > 10)
);

